---
title: "采用贝叶斯序列分析确定样本量"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
documentclass: ctexart
output:
  html_document:
    fig_caption: true
    number_sections: true
    toc: true
  pdf_document:
    toc: true
geometry: left=2cm,right=2cm,top=2cm,bottom=2cm
editor_options:
  markdown:
    wrap: 72
---

-   停止规则：
    -   贝叶斯因子阈值确定为10
    -   最小样本量40，最大样本量70
-   研究假设
    -   匹配任务
        -   关联类型的主效应
        -   关联类型与难度的交互作用
    -   辨别任务
        -   关联类型的主效应
        -   关联类型与难度的交互作用
-   **研究的关键假设：**在任意一个知觉辨别的难度下，当知觉辨别任务不直接与自我相关时，是否仍然存在自我优势效应？这一关键研究假设是本研究决定何时停止数据收集的关键效应量
-   在此处只检验是否存在交互作用


```{r}
rm(list = ls())
```

下载和安装需要的R语言程序包

```{r message=FALSE, warning=FALSE}
# install.packages(c("tidyverse", "BayesFactor", "here"))
library(BayesFactor)#计算t检验和方差分析的贝叶斯因子
packageVersion("BayesFactor")
library(tidyverse)
library(showtext)#解决中文字体无法显示问题
library(latex2exp)#latex语法
# font_add("song", 
         # "/System/Library/Fonts/Supplemental/Songti.ttc")
##从系统增加宋体字
showtext_auto()
library(here)
here()
options(scipen = 9)#将科学计数法改为在万后9位
set.seed(1234)
```

加载函数

```{r}
source(here::here("SPE_analysis/2_Code/Functions/Function_bf_avo.R"))
source(here::here("SPE_analysis/2_Code/Functions/Function_bf_pairwise_tests.R"))
source(here::here("SPE_analysis/2_Code/Functions/Function_plot_avo.R"))
source(here::here("SPE_analysis/2_Code/Functions/Function_plot_ttest.R"))
```

## 读取清洗后的数据

```{r}
# 文件路径和文件名根据实际情况调整
# 设置目标文件夹相对路径
folder_path <- "../3_Data/exp1a/CleanData"

# 列出目标文件
file_list <- list.files(
  path = folder_path,
  pattern = "*df_.*\\.csv$", full.names = TRUE
) # 这里根据实际命名进行修改


# 初始化一个列表用于存储数据框
df_list <- list()
for (i in seq_along(file_list)) {
  # 去掉文件后缀，作为数据框在列表中的名称
  df_name <- tools::file_path_sans_ext(file_list[i])
  df_list[[df_name]] <- read.csv(file_list[i])
}

# 将列表中的数据框单独赋值到全局环境（可选）
# list2env(df_list, envir = .GlobalEnv)

# 定义需要转换的变量名
factor_vars <- c("subj_idx", "association", "difficulty")

# 提取数据框
df_color_diff_match <- df_list[[1]] 
df_color_diff_rdk <- df_list[[2]] 
df_color_match <- df_list[[3]] %>% 
  dplyr::mutate(dplyr::across(all_of(factor_vars), as.factor))
df_color_rdk <- df_list[[4]] %>% 
  dplyr::mutate(dplyr::across(all_of(factor_vars), as.factor))
df_motion_diff_match <- df_list[[5]]
df_motion_diff_rdk <- df_list[[6]]
df_motion_match <- df_list[[7]] %>% 
  dplyr::mutate(dplyr::across(all_of(factor_vars), as.factor))
df_motion_rdk <- df_list[[8]] %>% 
  dplyr::mutate(dplyr::across(all_of(factor_vars), as.factor))
```


## BF 值计算

### 运动组

#### 匹配任务

##### 关联类型主效应

###### ACC

```{r}
bfs_association_mm_acc <- bf_aov(df_motion_match, 'acc', 'association')
bfs_association_mm_acc
```

**可视化**

```{r}
plot_bfs_association <- plot_aov(bfs_association_mm_acc, 'bfs_a', 'Association effect: motion match task(ACC)')
plot_bfs_association

plot_bfs_int <- plot_aov(bfs_association_mm_acc, 'bfs_int', 'Interaction: motion match task(ACC)')
plot_bfs_int
```

###### RT

```{r}
bfs_association_mm_rt <- bf_aov(df_motion_match, 'rt')
bfs_association_mm_rt
```

**可视化**

```{r}
plot_bfs_association <- plot_aov(bfs_association_mm_rt, 'bfs_a', 'Association effect: motion match task(RT)')
plot_bfs_association

plot_bfs_int <- plot_aov(bfs_association_mm_rt, 'bfs_int', 'Interaction: motion match task(RT)')
plot_bfs_int
```


#### 辨别任务

##### ACC

```{r}
bfs_association_mr_acc <- bf_aov(df_motion_rdk, 'acc')
bfs_association_mr_acc
```

**可视化**

```{r}
plot_bfs_association <- plot_aov(bfs_association_mr_acc, 'bfs_a', 'Association effect: motion rdk task(ACC)')
plot_bfs_association

plot_bfs_int <- plot_aov(bfs_association_mr_acc, 'bfs_int', 'Interaction: motion rdk task(ACC)')
plot_bfs_int
```

##### RT

```{r}
bfs_association_mr_rt <- bf_aov(df_motion_rdk, 'rt')
bfs_association_mr_rt
```

**可视化**

```{r}
plot_bfs_association <- plot_aov(bfs_association_mr_rt, 'bfs_a', 'Association effect: motion rdk task(RT)')
plot_bfs_association

plot_bfs_int <- plot_aov(bfs_association_mr_rt, 'bfs_int', 'Interaction: motion rdk task(RT)')
plot_bfs_int
```


### 颜色组

#### 匹配任务

##### ACC

```{r}
bfs_association_cm_acc <- bf_aov(df_color_match, 'acc', 'association')
bfs_association_cm_acc
```

**可视化**

```{r}
plot_bfs_association <- plot_aov(bfs_association_cm_acc, 'bfs_a', 'Association effect: color match task(ACC)')
plot_bfs_association

plot_bfs_int <- plot_aov(bfs_association_cm_acc, 'bfs_int', 'Interaction: color match task(ACC)')
plot_bfs_int
```

###### RT

```{r}
bfs_association_cm_rt <- bf_aov(df_color_match, 'rt', 'association')
bfs_association_cm_rt
```

**可视化**

```{r}
plot_bfs_association <- plot_aov(bfs_association_cm_rt, 'bfs_a', 'Association effect: color match trial(RT)')
plot_bfs_association

plot_bfs_int <- plot_aov(bfs_association_cm_rt, 'bfs_int', 'Interaction: color match trial(RT)')
plot_bfs_int
```


#### 辨别任务

##### ACC

```{r}
bfs_association_cr_acc <- bf_aov(df_color_rdk, 'acc', 'association')
bfs_association_cr_acc
```

**可视化**

```{r}
plot_bfs_association <- plot_aov(bfs_association_cr_acc, 'bfs_a', 'Association effect: color rdk task(ACC)')
plot_bfs_association

plot_bfs_int <- plot_aov(bfs_association_cr_acc, 'bfs_int', 'Interaction: color rdk task(ACC)')
plot_bfs_int
```

###### RT

```{r}
bfs_association_cr_rt <- bf_aov(df_color_rdk, 'rt', 'association')
bfs_association_cr_rt
```

**可视化**

```{r}
plot_bfs_association <- plot_aov(bfs_association_cr_rt, 'bfs_a', 'Association effect: color rdk task(RT)')
plot_bfs_association

plot_bfs_int <- plot_aov(bfs_association_cr_rt, 'bfs_int', 'Interaction: color rdk task(RT)')
plot_bfs_int
```


**End**
