---
title: "Analysis of exp1 (motion)"
author: "wusiyu, wujiaqi"
date: "2026-01-23"
output: html_document
---

# 环境与R包配置,‘
```{r}
# 配置环境
rm(list = ls())   # 清除当前工作环境中所有对象（变量、函数等）

if (.Platform$OS.type == 'windows') {
        Sys.setlocale(category = 'LC_ALL','en_US.UTF-8')   # 使用UTF-8编码
} 

# 安装cmdstanr作为后端
if (!require(cmdstanr)){
        install.packages("cmdstanr", repos = c('https://stan-dev.r-universe.dev', getOption("repos")))
        library(cmdstanr)
}

# set_cmdstan_path('C:/Users/HW/.cmdstan/cmdstan-2.36.0')   # 设置cmdstan路径：填写包的安装位置所在路径

# setwd("C:/1_Postgraduate/2_Lab/1_My_JC_Reports/2_methods/Tmp_BHM")   # 设置工作目录，自定义
curDir = getwd()   # 获取当前工作路径

set.seed(42)   # 随机种子，确保结果可复现
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)# 设置缓存，若随机数未变化则不重复运行已运行的代码块


# 配置R包
if (!require(pacman)){
        install.packages("pacman")
        library(pacman)
}

pacman::p_load(
  "tidyverse",  # 数据处理
  "ggplot2", # 数据可视化
  "brms", # 贝叶斯建模
  "bayesplot",  # 贝叶斯绘图
  "bridgesampling",   # 计算贝叶斯因子
  "papaja"   # 论文格式
)
```

# 数据预处理
```{r data_preprocess}
# load in function
# source(here::here("SPE_analysis", "Code", "Functions", "Function_run_lmer.R"))
# 改为相对路径
source("../../SPE_analysis/2_Code/Functions/Function_run_lmer.R")

# set paths
# dataPath = here::here("SPE_analysis/Data/exp1a/CleanData/")
# resultDir = here::here("SPE_analysis/Data/exp1a/CleanData/")
# 改为相对路径
dataPath <- "../../SPE_analysis/3_Data/exp1a/CleanData/"
resultDir <- "../../SPE_analysis/3_Data/exp1a/CleanData/"

# load in data
data_motion <- read.csv(file = file.path(dataPath, "data_motion.csv")) %>%
  dplyr::mutate(
    # R默认将因子第一个水平编码为0，其余为1，生成哑变量编码矩阵
    association = factor(association, levels = c("self", "other")),
    matchness = factor(isMatch, levels = c("match", "mismatch")),
    # difficulty = ordered(difficulty, levels = c("1", "2", "3", "4"))
)
data_color <- read.csv(file = file.path(dataPath, "data_color.csv"))
df_motion_match <- read.csv(file = file.path(dataPath, "df_motion_diff_match.csv"))
df_motion_rdk <- read.csv(file = file.path(dataPath, "df_motion_diff_rdk.csv"))
df_color_match <- read.csv(file = file.path(dataPath, "df_color_diff_match.csv"))
df_color_rdk <- read.csv(file = file.path(dataPath, "df_color_diff_rdk.csv"))

# 将难度转换为因子型(顺序变量)
# data_motion$difficulty <- ordered(data_motion$difficulty, levels = c("1", "2", "3", "4"))
# data_color$difficulty <- ordered(data_color$difficulty, levels = c("1", "2", "3", "4"))
# df_motion_match$difficulty <- ordered(df_motion_match$difficulty, levels = c("1", "2", "3", "4"))
# df_motion_rdk$difficulty <- ordered(df_motion_rdk$difficulty, levels = c("1", "2", "3", "4"))
# df_color_match$difficulty <- ordered(df_color_match$difficulty, levels = c("1", "2", "3", "4"))
# df_color_rdk$difficulty <- ordered(df_color_rdk$difficulty, levels = c("1", "2", "3", "4"))

# 将数据按任务进行拆分
data_color_match <- data_color %>%
  dplyr::filter(part %in% c('match_RDK'))
data_color_rdk <- data_color %>%
  dplyr::filter(part %in% c('RDK'))

data_motion_match <- data_motion %>%
  dplyr::filter(part %in% c('match_RDK'))
data_motion_rdk <- data_motion %>%
  dplyr::filter(part %in% c('RDK'))
```

# 1 检验假设一
## 1.1 匹配任务
### 1.1.1 RT
#### 1. 模型拟合：使用默认先验分布
```{r warning=FALSE}
m1_motion_match_rt <- data_motion_match %>%
  dplyr::filter(correct == 1) %>%
  brms::brm(
    rt ~ association*matchness+difficulty + (1 + association*matchness+difficulty|subj_idx),
    data = .,  # 模型设定随实验设计变化
    family=lognormal(),
    chains = 4,   
    warmup = 500,  
    iter = 2000,  
    thin = 1, 
    control = list(adapt_delta = .95),   # 用于减少采样发散
    cores = parallel::detectCores(),   # 使用所有可用核心
    backend = 'cmdstanr',   # rstan（默认）；cmdstanr：基于 Stan 的现代 C++ 实现
    save_pars = save_pars(all = TRUE),
    file = file.path(curDir, "glmmModels/m1_motion_match_rt")   # 缓存模型
)
```

#### 2. 模型评估
```{r}
summary(m1_motion_match_rt)
```

```{r traceplot}
mcmc_trace(m1_motion_match_rt, pars = c("b_Intercept", "b_associationother", "b_matchnessmismatch","b_associationother:matchnessmismatch", "sigma"))
```

#### 3. 后验预测
```{r}
pp_check(m1_motion_match_rt, type = "stat_grouped", group = "association")
```

#### 4. 统计推断

```{r}
# 固定效应，各个条件下反应时分布
df_match_rt_pop <- m1_motion_match_rt %>%
  tidybayes::gather_draws(`b_.*`, regex = TRUE) %>%
  dplyr::rename(term = .variable,
                pop_mean = .value) %>%  # gather_draws会将变量存储为1列，所有的值存储为另一列
  dplyr::ungroup() %>%
  dplyr::mutate(term = gsub("b_", "", term))%>%
  tidyr::pivot_wider(names_from = c(term), values_from = pop_mean) %>%   # long to wide
  # 计算各条件反应时分布
  dplyr::mutate(
    self_match = Intercept,   #  self和match作为基线              
    other_match = Intercept  + associationother,
    self_mismatch = Intercept  + matchnessmismatch,
    other_mismatch = Intercept + associationother + matchnessmismatch + `associationother:matchnessmismatch`
    )%>%
  dplyr::select(`.chain`, `.iteration`, `.draw`,
                self_match, other_match,
                self_mismatch, other_mismatch) %>%
  # wide to long
  tidyr::pivot_longer(cols = self_match:other_mismatch, names_to = "term", values_to =  "value") %>%  
  dplyr::mutate(term = factor(term, levels = c(
                'self_match', 'other_match', 
                'self_mismatch', 'other_mismatch'
  )),
  # log还原
  value = exp(value),
  value = value *1000)

df_match_rt_pop
```


```{r}
# 固定效应，条件间差异分布
df_match_rt_pop_diff_wide <- df_match_rt_pop %>%
  tidyr::pivot_wider(names_from = c(term), values_from = value) %>%
  dplyr::mutate(
    diff_os_match = other_match - self_match,
    diff_os_mismatch = other_mismatch - self_mismatch
  ) %>%
  dplyr::select(`.chain`, `.iteration`, `.draw`,
    diff_os_match, diff_os_mismatch)

df_match_rt_pop_diff_wide
```

```{r}
# 固定效应，后验分布描述
df_match_rt_fixed <- df_match_rt_pop%>%
  tidyr::pivot_wider(.,
                     id_cols = c('.chain', '.iteration', '.draw'),
                     names_from = term ) %>%
  dplyr::select(-c('.chain', '.iteration', '.draw')) %>%
  bayestestR::describe_posterior(.,
                                 ci = 0.95,
                                 ci_method = 'hdi',
                                 test = c("p_direction", "p_significance"),
                                 centrality = "median") %>%
  tidyr::separate(Parameter, c('association', 'matchness')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other')),
                matchness = factor(matchness, levels = c('match', 'mismatch')))

summary(df_match_rt_fixed)
```

```{r}
# 各条件中位数及可信区间

## 匹配条件
med_match_rt_self_match<- round(df_match_rt_fixed$Median[df_match_rt_fixed$association == 'self' & df_match_rt_fixed$matchness == 'match'], digits = 2)
ll_match_rt_self_match<- round(df_match_rt_fixed$CI_low[df_match_rt_fixed$association == 'self' & df_match_rt_fixed$matchness == 'match'], digits = 2)
ul_match_rt_self_match<- round(df_match_rt_fixed$CI_high[df_match_rt_fixed$association == 'self' & df_match_rt_fixed$matchness == 'match'], digits = 2)

med_match_rt_other_match<- round(df_match_rt_fixed$Median[df_match_rt_fixed$association == 'other' & df_match_rt_fixed$matchness == 'match'], digits = 2)
ll_match_rt_other_match<- round(df_match_rt_fixed$CI_low[df_match_rt_fixed$association == 'other' & df_match_rt_fixed$matchness == 'match'], digits = 2)
ul_match_rt_other_match<- round(df_match_rt_fixed$CI_high[df_match_rt_fixed$association == 'other' & df_match_rt_fixed$matchness == 'match'], digits = 2)


## 不匹配条件
med_match_rt_self_mismatch<- round(df_match_rt_fixed$Median[df_match_rt_fixed$association == 'self' & df_match_rt_fixed$matchness == 'mismatch'], digits = 2)
ll_match_rt_self_mismatch<- round(df_match_rt_fixed$CI_low[df_match_rt_fixed$association == 'self' & df_match_rt_fixed$matchness == 'mismatch'], digits = 2)
ul_match_rt_self_mismatch<- round(df_match_rt_fixed$CI_high[df_match_rt_fixed$association == 'self' & df_match_rt_fixed$matchness == 'mismatch'], digits = 2)

med_match_rt_other_mismatch<- round(df_match_rt_fixed$Median[df_match_rt_fixed$association == 'other' & df_match_rt_fixed$matchness == 'mismatch'], digits = 2)
ll_match_rt_other_mismatch<- round(df_match_rt_fixed$CI_low[df_match_rt_fixed$association == 'other' & df_match_rt_fixed$matchness == 'mismatch'], digits = 2)
ul_match_rt_other_mismatch<- round(df_match_rt_fixed$CI_high[df_match_rt_fixed$association == 'other' & df_match_rt_fixed$matchness == 'mismatch'], digits = 2)
```

```{r}
# 基于sexit框架进行统计推断（改）
bayestestR::sexit(df_match_rt_pop_diff_wide[,c(4:5)])
```


#### 5. 结果可视化

```{r}
# p1：绘制各个条件下反应时后验分布（固定效应）

## 固定效应均值
vlines <- df_match_rt_pop %>%
  tidyr::separate(term, c('association', 'matchness')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other'), labels = c("自我", "他人")),
                matchness = factor(matchness, levels = c('match', 'mismatch'), labels = c("匹配", "不匹配"))) %>%
  dplyr::group_by(association, matchness) %>%
  dplyr::summarize(Mean = mean(value))


## 各个条件RT后验分布
p_match_rt <- df_match_rt_pop %>%
  tidyr::separate(term, c('association', 'matchness')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other'), labels = c("自我", "他人")),
                matchness = factor(matchness, levels = c('match', 'mismatch'), labels = c("匹配", "不匹配"))) %>%
  ggplot2::ggplot(., aes(x = value, color = association)) +
  tidybayes::stat_halfeye(aes(fill = association), alpha = 0.6) +
  ggplot2::geom_vline(data = vlines,
             aes(xintercept = Mean, color = association),
             linetype = "dashed") +
  ggplot2::facet_wrap( ~ matchness, nrow = 2) +
  ggplot2::scale_colour_brewer(palette = "Dark2") +
  ggplot2::scale_fill_brewer(palette = "Dark2")+
  ggplot2::labs(x = expression('反应时后验分布'),
                color = "关联类型",
                fill = "关联类型",
                )


# theme_apa()
p_match_rt

# ggsave(file.path(figDir, "motion_match_RT.png"))
```

```{r}
# p2：绘制各个条件反应时差异的后验分布（固定效应）

# 绘图数据
df_match_rt_pop_diff <- df_match_rt_pop_diff_wide %>%
  # wide to long
  tidyr::pivot_longer(
    cols = diff_os_match:diff_os_mismatch,
    names_to = "term_diff",
    values_to =  "value"
  ) %>%
  dplyr::mutate(term_diff = factor(
    term_diff,
    levels = c(
      'diff_os_match','diff_os_mismatch'),
    labels = c(
      "(RT[他人] - RT[自我])[匹配]",
      "(RT[他人] - RT[自我])[不匹配]"
    )
  ))


p_match_rt_diff <- df_match_rt_pop_diff %>%
  ggplot2::ggplot(aes(x = value, fill = after_stat(x > 0))) +   # RT：self快于friend/stranger,用RT长的-短的
  tidybayes::stat_halfeye() +
  geom_vline(xintercept = 0, linetype = "dashed") + # 添加x=0的垂线
  scale_fill_manual(
    values = c('#E74C3C', '#2980B9'),# 蓝色出现在true组，红色出现在false组
    breaks = c(TRUE, FALSE),
    name = "反应时差异" ,
    labels = c(">0", "<0")# 标签yes表示x<0
  ) +
  xlab("各条件反应时差异后验分布") +
 facet_wrap( ~ term_diff, nrow = 2, 
              labeller = labeller(term_diff = label_parsed))

p_match_rt_diff


# ggsave(file.path(figDir, "motion_match_RT_diff.png"))
```

### 1.1.2 ACC
#### 1. 模型拟合
```{r}
m2_motion_match_acc <- data_motion_match %>%
  # dplyr::mutate(correct = ifelse(correct == "true", 1, 0)) %>%
  brms::brm(
    correct ~ association*matchness + difficulty + (1 + association*matchness + difficulty|subj_idx),
    data = .,  # 模型设定随实验设计变化
    family = "bernoulli",
    chains = 4,   
    warmup = 500,  
    iter = 2000,  
    thin = 1, 
    control = list(adapt_delta = .95),   # 用于减少采样发散
    cores = parallel::detectCores(),   # 使用所有可用核心
    backend = 'cmdstanr',   # rstan（默认）；cmdstanr：基于 Stan 的现代 C++ 实现，速度更快且更稳定
    save_pars = save_pars(all = TRUE),
    file = file.path(curDir, "glmmModels/m2_motion_match_acc")   # 缓存模型
)
```

#### 2. 模型评估
```{r}
summary(m2_motion_match_acc)
```


#### 3. 后验预测
```{r}
pp_check(m2_motion_match_acc, type = "stat_grouped", group = "association")
```


#### 4. 统计推断

```{r}
# 固定效应，各个条件下反应时分布
df_match_acc_pop <- m2_motion_match_acc %>%
  tidybayes::gather_draws(`b_.*`, regex = TRUE) %>%
  dplyr::rename(term = .variable,
                pop_mean = .value) %>%  # gather_draws会将变量存储为1列，所有的值存储为另一列
  dplyr::ungroup() %>%
  dplyr::mutate(term = gsub("b_", "", term))%>%
  tidyr::pivot_wider(names_from = c(term), values_from = pop_mean) %>%   # long to wide
  # 计算各条件反应时分布
  dplyr::mutate(
    self_match = Intercept,   #  self和match作为基线              
    other_match = Intercept  + associationother,
    self_mismatch = Intercept  + matchnessmismatch,
    other_mismatch = Intercept + associationother + matchnessmismatch + `associationother:matchnessmismatch`
    )%>%
  dplyr::select(`.chain`, `.iteration`, `.draw`,
                self_match, other_match,
                self_mismatch, other_mismatch) %>%
  # wide to long
  tidyr::pivot_longer(cols = self_match:other_mismatch, names_to = "term", values_to =  "value") %>%  
  dplyr::mutate(term = factor(term, levels = c(
                'self_match', 'other_match', 
                'self_mismatch', 'other_mismatch'
  )))
  # log还原
  # value = exp(value),
  # value = value *1000)

df_match_acc_pop
```
```{r}
# 固定效应，条件间差异分布
df_match_acc_pop_diff_wide <- df_match_acc_pop %>%
  tidyr::pivot_wider(names_from = c(term), values_from = value) %>%
  dplyr::mutate(
    diff_so_match = self_match - other_match,
    diff_so_mismatch = self_mismatch - other_mismatch
  ) %>%
  dplyr::select(`.chain`, `.iteration`, `.draw`,
    diff_so_match, diff_so_mismatch)

df_match_acc_pop_diff_wide
```

```{r}
# 固定效应，后验分布描述
df_match_acc_fixed <- df_match_acc_pop%>%
  tidyr::pivot_wider(.,
                     id_cols = c('.chain', '.iteration', '.draw'),
                     names_from = term ) %>%
  dplyr::select(-c('.chain', '.iteration', '.draw')) %>%
  bayestestR::describe_posterior(.,
                                 ci = 0.95,
                                 ci_method = 'hdi',
                                 test = c("p_direction", "p_significance"),
                                 centrality = "median") %>%
  tidyr::separate(Parameter, c('association', 'matchness')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other')),
                matchness = factor(matchness, levels = c('match', 'mismatch')))

summary(df_match_acc_fixed)
```

```{r}
# 各条件中位数及可信区间

## 匹配条件
med_match_acc_self_match<- round(df_match_acc_fixed$Median[df_match_acc_fixed$association == 'self' & df_match_acc_fixed$matchness == 'match'], digits = 2)
ll_match_acc_self_match<- round(df_match_acc_fixed$CI_low[df_match_acc_fixed$association == 'self' & df_match_acc_fixed$matchness == 'match'], digits = 2)
ul_match_acc_self_match<- round(df_match_acc_fixed$CI_high[df_match_acc_fixed$association == 'self' & df_match_acc_fixed$matchness == 'match'], digits = 2)

med_match_acc_other_match<- round(df_match_acc_fixed$Median[df_match_acc_fixed$association == 'other' & df_match_acc_fixed$matchness == 'match'], digits = 2)
ll_match_acc_other_match<- round(df_match_acc_fixed$CI_low[df_match_acc_fixed$association == 'other' & df_match_acc_fixed$matchness == 'match'], digits = 2)
ul_match_acc_other_match<- round(df_match_acc_fixed$CI_high[df_match_acc_fixed$association == 'other' & df_match_acc_fixed$matchness == 'match'], digits = 2)


## 不匹配条件
med_match_acc_self_mismatch<- round(df_match_acc_fixed$Median[df_match_acc_fixed$association == 'self' & df_match_acc_fixed$matchness == 'mismatch'], digits = 2)
ll_match_acc_self_mismatch<- round(df_match_acc_fixed$CI_low[df_match_acc_fixed$association == 'self' & df_match_acc_fixed$matchness == 'mismatch'], digits = 2)
ul_match_acc_self_mismatch<- round(df_match_acc_fixed$CI_high[df_match_acc_fixed$association == 'self' & df_match_acc_fixed$matchness == 'mismatch'], digits = 2)

med_match_acc_other_mismatch<- round(df_match_acc_fixed$Median[df_match_acc_fixed$association == 'other' & df_match_acc_fixed$matchness == 'mismatch'], digits = 2)
ll_match_acc_other_mismatch<- round(df_match_acc_fixed$CI_low[df_match_acc_fixed$association == 'other' & df_match_acc_fixed$matchness == 'mismatch'], digits = 2)
ul_match_acc_other_mismatch<- round(df_match_acc_fixed$CI_high[df_match_acc_fixed$association == 'other' & df_match_acc_fixed$matchness == 'mismatch'], digits = 2)
```

```{r}
# 基于sexit框架进行统计推断（改）
bayestestR::sexit(df_match_acc_pop_diff_wide[,c(4:5)])
```

#### 5. 结果可视化

```{r}
# p1：绘制各个条件下反应时后验分布（固定效应）

## 固定效应均值
vlines <- df_match_acc_pop %>%
  tidyr::separate(term, c('association', 'matchness')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other'), labels = c("自我", "他人")),
                matchness = factor(matchness, levels = c('match', 'mismatch'), labels = c("匹配", "不匹配"))) %>%
  dplyr::group_by(association, matchness) %>%
  dplyr::summarize(Mean = mean(value))


## 各个条件RT后验分布
p_match_acc <- df_match_acc_pop %>%
  tidyr::separate(term, c('association', 'matchness')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other'), labels = c("自我", "他人")),
                matchness = factor(matchness, levels = c('match', 'mismatch'), labels = c("匹配", "不匹配"))) %>%
  ggplot2::ggplot(., aes(x = value, color = association)) +
  tidybayes::stat_halfeye(aes(fill = association), alpha = 0.6) +
  ggplot2::geom_vline(data = vlines,
             aes(xintercept = Mean, color = association),
             linetype = "dashed") +
  ggplot2::facet_wrap( ~ matchness, nrow = 2) +
  ggplot2::scale_colour_brewer(palette = "Dark2") +
  ggplot2::scale_fill_brewer(palette = "Dark2")+
  ggplot2::labs(x = expression('反应时后验分布'),
                color = "关联类型",
                fill = "关联类型",
                )


# theme_apa()
p_match_acc

# ggsave(file.path(figDir, "motion_match_acc.png"))
```

```{r}
# p2：绘制各个条件反应时差异的后验分布（固定效应）

# 绘图数据
df_match_acc_pop_diff <- df_match_acc_pop_diff_wide %>%
  # wide to long
  tidyr::pivot_longer(
    cols = diff_so_match:diff_so_mismatch,
    names_to = "term_diff",
    values_to =  "value"
  ) %>%
  dplyr::mutate(term_diff = factor(
    term_diff,
    levels = c(
      'diff_so_match','diff_so_mismatch'),
    labels = c(
      "(correct[自我] - correct[他人])[匹配]",
      "(correct[自我] - correct[他人])[不匹配]"
    )
  ))


p_match_acc_diff <- df_match_acc_pop_diff %>%
  ggplot2::ggplot(aes(x = value, fill = after_stat(x > 0))) +   # RT：self快于friend/stranger,用RT长的-短的
  tidybayes::stat_halfeye() +
  geom_vline(xintercept = 0, linetype = "dashed") + # 添加x=0的垂线
  scale_fill_manual(
    values = c('#E74C3C', '#2980B9'),# 蓝色出现在true组，红色出现在false组
    breaks = c(TRUE, FALSE),
    name = "正确率差异" ,
    labels = c(">0", "<0")# 标签yes表示x<0
  ) +
  xlab("各条件正确率差异后验分布") +
 facet_wrap( ~ term_diff, nrow = 2, 
              labeller = labeller(term_diff = label_parsed))

p_match_acc_diff


# ggsave(file.path(figDir, "motion_match_acc_diff.png"))
```

## 1.2 辨别任务
### 1.2.1 RT
#### 1. 模型拟合：使用默认先验分布
```{r warning=FALSE}
m3_motion_rdk_rt <- data_motion_rdk %>%
  dplyr::filter(correct == 1) %>%
  brms::brm(
    rt ~ association + difficulty + (1 + association + difficulty|subj_idx),
    data = .,  # 模型设定随实验设计变化
    family=lognormal(),
    chains = 4,   
    warmup = 500,  
    iter = 2000,  
    thin = 1, 
    control = list(adapt_delta = .95),   # 用于减少采样发散
    cores = parallel::detectCores(),   # 使用所有可用核心
    backend = 'cmdstanr',   # rstan（默认）；cmdstanr：基于 Stan 的现代 C++ 
    save_pars = save_pars(all = TRUE),
    file = file.path(curDir, "glmmModels/m3_motion_rdk_rt")   # 缓存模型
)
```

#### 2. 模型评估
```{r}
summary(m3_motion_rdk_rt)
```

#### 3. 后验预测
```{r}
pp_check(m3_motion_rdk_rt, type = "stat_grouped", group = "association")
```

#### 4. 统计推断

```{r}
# 固定效应，各个条件下反应时分布
df_rdk_rt_pop <- m3_motion_rdk_rt %>%
  tidybayes::gather_draws(`b_.*`, regex = TRUE) %>%
  dplyr::rename(term = .variable,
                pop_mean = .value) %>%  # gather_draws会将变量存储为1列，所有的值存储为另一列
  dplyr::ungroup() %>%
  dplyr::mutate(term = gsub("b_", "", term))%>%
  tidyr::pivot_wider(names_from = c(term), values_from = pop_mean) %>%   # long to wide
  # 计算各条件反应时分布
  dplyr::mutate(
    self = Intercept,   #  self作为基线              
    other = Intercept  + associationother
    )%>%
  dplyr::select(`.chain`, `.iteration`, `.draw`, self, other) %>%
  # wide to long
  tidyr::pivot_longer(cols = self:other, names_to = "term", values_to =  "value") %>%  
  dplyr::mutate(term = factor(term, levels = c(
                'self', 'other')),
  # log还原
  value = exp(value),
  value = value *1000)

df_rdk_rt_pop
```

```{r}
# 固定效应，条件间差异分布
df_rdk_rt_pop_diff_wide <- df_rdk_rt_pop %>%
  tidyr::pivot_wider(names_from = c(term), values_from = value) %>%
  dplyr::mutate(
    diff_os_rdk = other - self
  ) %>%
  dplyr::select(`.chain`, `.iteration`, `.draw`, diff_os_rdk)

df_rdk_rt_pop_diff_wide
```

```{r}
# 固定效应，后验分布描述
df_rdk_rt_fixed <- df_rdk_rt_pop%>%
  tidyr::pivot_wider(.,
                     id_cols = c('.chain', '.iteration', '.draw'),
                     names_from = term ) %>%
  dplyr::select(-c('.chain', '.iteration', '.draw')) %>%
  bayestestR::describe_posterior(.,
                                 ci = 0.95,
                                 ci_method = 'hdi',
                                 test = c("p_direction", "p_significance"),
                                 centrality = "median") %>%
  tidyr::separate(Parameter, c('association')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other')))

summary(df_rdk_rt_fixed)
```

```{r}
# 各条件中位数及可信区间
med_rdk_rt_self<- round(df_rdk_rt_fixed$Median[df_rdk_rt_fixed$association == 'self'], digits = 2)
ll_rdk_rt_self<- round(df_rdk_rt_fixed$CI_low[df_rdk_rt_fixed$association == 'self'], digits = 2)
ul_rdk_rt_self<- round(df_rdk_rt_fixed$CI_high[df_rdk_rt_fixed$association == 'self'], digits = 2)

med_rdk_rt_other<- round(df_rdk_rt_fixed$Median[df_rdk_rt_fixed$association == 'other'], digits = 2)
ll_rdk_rt_other<- round(df_rdk_rt_fixed$CI_low[df_rdk_rt_fixed$association == 'other'], digits = 2)
ul_rdk_rt_other<- round(df_rdk_rt_fixed$CI_high[df_rdk_rt_fixed$association == 'other'], digits = 2)
```

```{r}
# 基于sexit框架进行统计推断（改）
bayestestR::sexit(df_rdk_rt_pop_diff_wide[,c(3:4)])
```

#### 5. 结果可视化

```{r}
# p1：绘制各个条件下反应时后验分布（固定效应）

## 固定效应均值
vlines <- df_rdk_rt_pop %>%
  tidyr::separate(term, c('association')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other'), labels = c("自我", "他人"))) %>%
  dplyr::group_by(association) %>%
  dplyr::summarize(Mean = mean(value))


## 各个条件RT后验分布
p_rdk_rt <- df_rdk_rt_pop %>%
  tidyr::separate(term, c('association')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other'), labels = c("自我", "他人"))) %>%
  ggplot2::ggplot(., aes(x = value, color = association)) +
  tidybayes::stat_halfeye(aes(fill = association), alpha = 0.6) +
  ggplot2::geom_vline(data = vlines,
             aes(xintercept = Mean, color = association),
             linetype = "dashed") +
  # ggplot2::facet_wrap( ~ matchness, nrow = 1) +
  ggplot2::scale_colour_brewer(palette = "Dark2") +
  ggplot2::scale_fill_brewer(palette = "Dark2")+
  ggplot2::labs(x = expression('反应时后验分布'),
                color = "关联类型",
                fill = "关联类型",
                )


# theme_apa()
p_rdk_rt

# ggsave(file.path(figDir, "motion_rdk_RT.png"))
```

```{r}
# p2：绘制各个条件反应时差异的后验分布（固定效应）

# 绘图数据
df_rdk_rt_pop_diff <- df_rdk_rt_pop_diff_wide %>%
  # wide to long
  tidyr::pivot_longer(
    cols = diff_os_rdk,
    names_to = "term_diff",
    values_to =  "value"
  ) %>%
  dplyr::mutate(term_diff = factor(
    term_diff,
    levels = c(
      'diff_os_rdk'),
    labels = c(
      "(RT[他人] - RT[自我])"
    )
  ))


p_rdk_rt_diff <- df_rdk_rt_pop_diff %>%
  ggplot2::ggplot(aes(x = value, fill = after_stat(x > 0))) +   # RT：self快于friend/stranger,用RT长的-短的
  tidybayes::stat_halfeye() +
  geom_vline(xintercept = 0, linetype = "dashed") + # 添加x=0的垂线
  scale_fill_manual(
    values = c('#E74C3C', '#2980B9'),# 蓝色出现在true组，红色出现在false组
    breaks = c(TRUE, FALSE),
    name = "反应时差异" ,
    labels = c(">0", "<0")# 标签yes表示x<0
  ) +
  xlab("各条件反应时差异后验分布") +
 facet_wrap( ~ term_diff, nrow = 2, 
              labeller = labeller(term_diff = label_parsed))

p_rdk_rt_diff


# ggsave(file.path(figDir, "motion_rdk_RT_diff.png"))
```

### 1.2.2 ACC
#### 1. 模型拟合：使用默认先验分布
```{r warning=FALSE}
# iter=1000,Total execution time: 852.2 seconds..18mins
m4_motion_rdk_acc <- data_motion_rdk %>%
  # dplyr::mutate(correct = ifelse(correct == "true", 1, 0)) %>%
  brms::brm(
    correct ~ association + difficulty + (1 + association + difficulty|subj_idx),
    data = .,  # 模型设定随实验设计变化
    family = "bernoulli",
    chains = 4,   
    warmup = 500,  
    iter = 2000,  
    thin = 1, 
    control = list(adapt_delta = .95),   # 用于减少采样发散
    cores = parallel::detectCores(),   # 使用所有可用核心
    backend = 'cmdstanr',   # rstan（默认）；cmdstanr：基于 Stan 的现代 C++ 
    save_pars = save_pars(all = TRUE),
    file = file.path(curDir, "glmmModels/m4_motion_rdk_acc")   # 缓存模型
)
```

#### 2. 模型评估
```{r}
summary(m4_motion_rdk_acc)
```

#### 3. 后验预测
```{r}
pp_check(m4_motion_rdk_acc, type = "stat_grouped", group = "association")
```

#### 4. 统计推断

```{r}
# 固定效应，各个条件下反应时分布
df_rdk_acc_pop <- m4_motion_rdk_acc %>%
  tidybayes::gather_draws(`b_.*`, regex = TRUE) %>%
  dplyr::rename(term = .variable,
                pop_mean = .value) %>%  # gather_draws会将变量存储为1列，所有的值存储为另一列
  dplyr::ungroup() %>%
  dplyr::mutate(term = gsub("b_", "", term))%>%
  tidyr::pivot_wider(names_from = c(term), values_from = pop_mean) %>%   # long to wide
  # 计算各条件反应时分布
  dplyr::mutate(
    self = Intercept,   #  self和match作为基线              
    other = Intercept  + associationother)%>%
  dplyr::select(`.chain`, `.iteration`, `.draw`, self, other) %>%
  # wide to long
  tidyr::pivot_longer(cols = self:other, names_to = "term", values_to =  "value") %>%  
  dplyr::mutate(term = factor(term, levels = c(
                'self', 'other')))
  # log还原
  # value = exp(value),
  # value = value *1000)

df_rdk_acc_pop
```
```{r}
# 固定效应，条件间差异分布
df_rdk_acc_pop_diff_wide <- df_rdk_acc_pop %>%
  tidyr::pivot_wider(names_from = c(term), values_from = value) %>%
  dplyr::mutate(
    diff_so_rdk = self - other
  ) %>%
  dplyr::select(`.chain`, `.iteration`, `.draw`, diff_so_rdk)

df_rdk_acc_pop_diff_wide
```

```{r}
# 固定效应，后验分布描述
df_rdk_acc_fixed <- df_rdk_acc_pop%>%
  tidyr::pivot_wider(.,
                     id_cols = c('.chain', '.iteration', '.draw'),
                     names_from = term ) %>%
  dplyr::select(-c('.chain', '.iteration', '.draw')) %>%
  bayestestR::describe_posterior(.,
                                 ci = 0.95,
                                 ci_method = 'hdi',
                                 test = c("p_direction", "p_significance"),
                                 centrality = "median") %>%
  tidyr::separate(Parameter, c('association')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other')))

summary(df_rdk_acc_fixed)
```

```{r}
# 各条件中位数及可信区间
med_rdk_acc_self<- round(df_rdk_acc_fixed$Median[df_rdk_acc_fixed$association == 'self'], digits = 2)
ll_rdk_acc_self<- round(df_rdk_acc_fixed$CI_low[df_rdk_acc_fixed$association == 'self'], digits = 2)
ul_rdk_acc_self<- round(df_rdk_acc_fixed$CI_high[df_rdk_acc_fixed$association == 'self'], digits = 2)

med_rdk_acc_other<- round(df_rdk_acc_fixed$Median[df_rdk_acc_fixed$association == 'other'], digits = 2)
ll_rdk_acc_other<- round(df_rdk_acc_fixed$CI_low[df_rdk_acc_fixed$association == 'other'], digits = 2)
ul_rdk_acc_other<- round(df_rdk_acc_fixed$CI_high[df_rdk_acc_fixed$association == 'other'], digits = 2)
```

```{r}
# 基于sexit框架进行统计推断（改）
bayestestR::sexit(df_rdk_acc_pop_diff_wide[,c(3:4)])
```

#### 5. 结果可视化

```{r}
# p1：绘制各个条件下反应时后验分布（固定效应）

## 固定效应均值
vlines <- df_rdk_acc_pop %>%
  tidyr::separate(term, c('association')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other'), labels = c("自我", "他人"))) %>%
  dplyr::group_by(association) %>%
  dplyr::summarize(Mean = mean(value))


## 各个条件RT后验分布
p_rdk_acc <- df_rdk_acc_pop %>%
  tidyr::separate(term, c('association')) %>%
  dplyr::mutate(association = factor(association, levels = c('self', 'other'), labels = c("自我", "他人"))) %>%
  ggplot2::ggplot(., aes(x = value, color = association)) +
  tidybayes::stat_halfeye(aes(fill = association), alpha = 0.6) +
  ggplot2::geom_vline(data = vlines,
             aes(xintercept = Mean, color = association),
             linetype = "dashed") +
  # ggplot2::facet_wrap( ~ matchness, nrow = 1) +
  ggplot2::scale_colour_brewer(palette = "Dark2") +
  ggplot2::scale_fill_brewer(palette = "Dark2")+
  ggplot2::labs(x = expression('正确率后验分布'),
                color = "关联类型",
                fill = "关联类型",
                )


# theme_apa()
p_rdk_acc

# ggsave(file.path(figDir, "motion_rdk_acc.png"))
```


```{r}
# p2：绘制各个条件反应时差异的后验分布（固定效应）

# 绘图数据
df_rdk_acc_pop_diff <- df_rdk_acc_pop_diff_wide %>%
  # wide to long
  tidyr::pivot_longer(
    cols = diff_so_rdk,
    names_to = "term_diff",
    values_to =  "value"
  ) %>%
  dplyr::mutate(term_diff = factor(
    term_diff,
    levels = c(
      'diff_so_rdk'),
    labels = c(
      "(correct[自我] - correct[他人])"
    )
  ))


p_rdk_acc_diff <- df_rdk_acc_pop_diff %>%
  ggplot2::ggplot(aes(x = value, fill = after_stat(x > 0))) +   # RT：self快于friend/stranger,用RT长的-短的
  tidybayes::stat_halfeye() +
  geom_vline(xintercept = 0, linetype = "dashed") + # 添加x=0的垂线
  scale_fill_manual(
    values = c('#E74C3C', '#2980B9'),# 蓝色出现在true组，红色出现在false组
    breaks = c(TRUE, FALSE),
    name = "正确率差异" ,
    labels = c(">0", "<0")# 标签yes表示x<0
  ) +
  xlab("各条件正确率差异后验分布") +
 facet_wrap( ~ term_diff, nrow = 2, 
              labeller = labeller(term_diff = label_parsed))

p_rdk_acc_diff


# ggsave(file.path(figDir, "motion_rdk_acc_diff.png"))
```

# 2 检验假设二(差异的差异)
## 2.1 匹配任务
### 2.1.1 RT

#### 1. 模型拟合
```{r warning=FALSE}
# 将难度编码为顺序变量，检查变化趋势
df_motion_match$difficulty <- ordered(df_motion_match$difficulty, levels = c("1", "2", "3", "4"))
# iter=1000,Total execution time: 852.2 seconds..18mins
m5_motion_match_rt <- df_motion_match %>%
  brms::brm(
    rt_diff_os ~ difficulty + (1 + difficulty|subj_idx),
    data = .,  # 模型设定随实验设计变化
    family = brmsfamily("gaussian", link = "identity", link_sigma = "log"),
    chains = 4,   
    warmup = 500,  
    iter = 2000,  
    thin = 1, 
    control = list(adapt_delta = .95),   # 用于减少采样发散
    cores = parallel::detectCores(),   # 使用所有可用核心
    backend = 'cmdstanr', 
    save_pars = save_pars(all = TRUE),
    file = file.path(curDir, "glmmModels/m5_motion_match_rt")   # 缓存模型
)
```

#### 2. 模型评估
```{r}
summary(m5_motion_match_rt)
summary(m5.2_motion_match_rt)
```

#### 3. 可视化
```{r plot motion match}
ggplot(df_motion_match, aes(x = difficulty, y = rt_diff_os, group = subj_idx)) +
  geom_line(alpha = 0.5) +
  stat_summary(aes(group = 1), fun = mean, geom = "line", color = "red", size = 1.5) + labs(title = "SPE Across Difficulty Levels(Motion match task RT)", y = "SPE", x = NULL) +
  papaja::theme_apa(base_size = 18) +
  # 设置y轴范围
  ylim(-300, 550) +
  # 在y=0处添加一条黑色虚线
  geom_hline(yintercept = 0, linetype = "dashed", color = "blue",size = 1) +
  scale_x_discrete(labels = c("very easy", "easy", "difficulty", "very difficulty"))
```

### 2.1.2 ACC

#### 1. 模型拟合
```{r warning=FALSE}
# iter=1000,Total execution time: 852.2 seconds..18mins
m6_motion_match_acc <- df_motion_match %>%
  brms::brm(
    acc_diff_so ~ difficulty + (1 + difficulty|subj_idx),
    data = .,  # 模型设定随实验设计变化
    # family=lognormal(),
    family = brmsfamily("gaussian", link = "identity", link_sigma = "log"),
    chains = 4,   
    warmup = 500,  
    iter = 2000,  
    thin = 1, 
    control = list(adapt_delta = .95),   # 用于减少采样发散
    cores = parallel::detectCores(),   # 使用所有可用核心
    backend = 'cmdstanr',   # rstan（默认）；cmdstanr：基于 Stan 的现代 C++ 实现，速度更快且更稳定
    save_pars = save_pars(all = TRUE),
    file = file.path(curDir, "glmmModels/m6_motion_match_acc")   # 缓存模型
)
```

#### 2. 模型评估
```{r}
summary(m6_motion_match_acc)
```

#### 3. 可视化
```{r plot motion match}
ggplot(df_motion_match, aes(x = difficulty, y = acc_diff_so, group = subj_idx)) +
  geom_line(alpha = 0.5) +
  stat_summary(aes(group = 1), fun = mean, geom = "line", color = "red", size = 1.5) + labs(title = "SPE Across Difficulty Levels(Motion match task ACC)", y = "SPE", x = NULL) +
  papaja::theme_apa(base_size = 18) +
  # 设置y轴范围
  # ylim(-300, 550) +
  # 在y=0处添加一条黑色虚线
  geom_hline(yintercept = 0, linetype = "dashed", color = "blue",size = 1) +
  scale_x_discrete(labels = c("very easy", "easy", "difficulty", "very difficulty"))
```

## 2.2 辨别任务
### 2.2.1 RT

#### 1. 模型拟合
```{r warning=FALSE}
df_motion_rdk$difficulty <- ordered(df_motion_rdk$difficulty, levels = c("1", "2", "3", "4"))

m7_motion_rdk_rt <- df_motion_rdk %>%
  brms::brm(
    rt_diff_os ~ difficulty + (1 + difficulty|subj_idx),
    data = .,  # 模型设定随实验设计变化
    # family=lognormal(),
    family = brmsfamily("gaussian", link = "identity", link_sigma = "log"),
    chains = 4,   
    warmup = 500,  
    iter = 2000,  
    thin = 1, 
    control = list(adapt_delta = .95),   # 用于减少采样发散
    cores = parallel::detectCores(),   # 使用所有可用核心
    backend = 'cmdstanr',   # rstan（默认）；cmdstanr：基于 Stan 的现代 C++ 实现，速度更快且更稳定
    save_pars = save_pars(all = TRUE),
    file = file.path(curDir, "glmmModels/m7_motion_rdk_rt")   # 缓存模型
)
```

#### 2. 模型评估
```{r}
summary(m7_motion_rdk_rt)
```

#### 3. 可视化
```{r plot motion rdk}
ggplot(df_motion_rdk, aes(x = difficulty, y = rt_diff_os, group = subj_idx)) +
  geom_line(alpha = 0.5) +
  stat_summary(aes(group = 1), fun = mean, geom = "line", color = "red", size = 1.5) + labs(title = "SPE Across Difficulty Levels(Motion rdk task RT)", y = "SPE") +
  papaja::theme_apa(base_size = 18) +
  # 设置y轴范围
  ylim(-200, 300) +
  # 在y=0处添加一条黑色虚线
  geom_hline(yintercept = 0, linetype = "dashed", color = "blue", size = 1) +
  scale_x_discrete(labels = c("very easy", "easy", "difficulty", "very difficulty"))
```

### 2.2.2 ACC

#### 1. 模型拟合
```{r warning=FALSE}
# iter=1000,Total execution time: 852.2 seconds..18mins
m8_motion_rdk_acc <- df_motion_rdk %>%
  brms::brm(
    acc_diff_so ~ difficulty + (1 + difficulty|subj_idx),
    data = .,  # 模型设定随实验设计变化
    # family=lognormal(),
    family = brmsfamily("gaussian", link = "identity", link_sigma = "log"),
    chains = 4,   
    warmup = 500,  
    iter = 2000,  
    thin = 1, 
    control = list(adapt_delta = .95),   # 用于减少采样发散
    cores = parallel::detectCores(),   # 使用所有可用核心
    backend = 'cmdstanr',   # rstan（默认）；cmdstanr：基于 Stan 的现代 C++ 实现，速度更快且更稳定
    save_pars = save_pars(all = TRUE),
    file = file.path(curDir, "glmmModels/m8_motion_rdk_acc")   # 缓存模型
)
```

#### 2. 模型评估
```{r}
summary(m8_motion_rdk_acc)
```

#### 3. 可视化
```{r plot motion rdk}
ggplot(df_motion_rdk, aes(x = difficulty, y = acc_diff_so, group = subj_idx)) +
  geom_line(alpha = 0.5) +
  stat_summary(aes(group = 1), fun = mean, geom = "line", color = "red", size = 1.5) + labs(title = "SPE Across Difficulty Levels(Motion rdk task ACC)", y = "SPE", x = NULL) +
  papaja::theme_apa(base_size = 18) +
  # 设置y轴范围
  # ylim(-300, 550) +
  # 在y=0处添加一条黑色虚线
  geom_hline(yintercept = 0, linetype = "dashed", color = "blue",size = 1) +
  scale_x_discrete(labels = c("very easy", "easy", "difficulty", "very difficulty"))
```

